[package]
name = "synth"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "0.72.1"
cc = "1.4.4"

[dependencies]
derive_more = { version = "2", default-features = false, features = [ "full" ] }
fixed = "1.29.0"
heapless = "0.9.3"
mockall = "0.14.0"
no_alloc = "0.1.0"
proptest = "1.8.0"
proptest-derive = "0.6.0"
scapegoat = "2.3.0"
spin = "0.10.0"
spin-lock = "0.2.1"

[dependencies.chumsky]
version = "0.11.1"
features = ["pratt"]

[features]
std = ["chumsky/std", "fixed/std"]
